//! Events emitted by the agent engine during execution. Used for streaming
//! updates to frontends (TUI, CLI, gateway).

use yips_core::message::ToolCall;

/// Events emitted during agent turn execution.
#[derive(Debug, Clone)]
pub enum AgentEvent {
    /// A token was generated by the LLM (streaming).
    Token(String),

    /// The LLM produced a complete text response.
    AssistantMessage(String),

    /// The LLM requested tool calls.
    ToolCallsRequested(Vec<ToolCall>),

    /// A tool execution started.
    ToolStart {
        tool_call_id: String,
        tool_name: String,
    },

    /// A tool execution completed.
    ToolComplete {
        tool_call_id: String,
        tool_name: String,
        success: bool,
        output: String,
    },

    /// A new round of the ReAct loop started.
    RoundStart { round: u32, max_rounds: u32 },

    /// The agent turn completed.
    TurnComplete {
        rounds_used: u32,
        final_response: Option<String>,
    },

    /// An error occurred during the turn.
    Error(String),
}
